micronaut:
  application:
    name: urlShortenerServer

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      logout:
        path: /users/signout
        enabled: true
    intercept-url-map:
      - pattern: /swagger/*
        access:
          - isAnonymous()
          - isAuthenticated()
      - pattern: /swagger-ui/*
        access:
          - isAnonymous()
          - isAuthenticated()

jackson:
  property-naming-strategy: SNAKE_CASE

url:
  proposal-count: 5
